name: Register person depictions

on:
  schedule:
    - cron: '0 3 * * 1-5'
  workflow_dispatch:

env:
  DUMPTHINGS_APIURL: https://pool.psychoinformatics.de/api

jobs:
  register_depictions:
    runs-on: debian-latest
    if: ${{ forgejo.repository == 'www/www-from-model' }}
    outputs:
      committed: ${{ steps.commit.outputs.committed }}

    steps:
      - name: Checkout
        uses: https://hub.datalad.org/forgejo/datalad-clone-action@v1
        with:
          recursive: true
          get_content: .
      - name: Prepare environment
        uses: ./.forgejo/actions/prep-metadata-query
      - name: Register depiction files
        run: |
          jq_output="$(
            dtc get-records ${DUMPTHINGS_APIURL} public -C XYZPerson \
            | qri filter-linked-pid --api-url ${DUMPTHINGS_APIURL} public xyzrins:. associated_with \
            | qri inject-links-pid --link about depictions --class XYZDepiction \
            | qri inline-records --api-url ${DUMPTHINGS_APIURL} -c public -p depictions::distributions \
            | code/get_person_depiction_urls.py
          )"
          if [[ -n "$jq_output" ]]; then
            while IFS=$'\t' read -r curie ext url; do
              git annex addurl --file="content/${curie}/portrait.${ext}" "$url" || \
                echo "addurl failed for $url, continuing..."
            done <<< "$jq_output"
            git annex push --no-content --cleanup
          fi
      - name: Deposit changes
        uses: ./.forgejo/actions/deposit-changes