name: Update website sources from knowledge pool

# run daily (5:15 on weekdays) and on manual dispatch
on:
  schedule:
    - cron: '0 1 * * 1-5'
  workflow_dispatch:

env:
  DUMPTHINGS_APIURL: https://pool.psychoinformatics.de/api
  QRI_RECORD_CACHE: /tmp/query-things-cache

jobs:
  create_pages:
    runs-on: debian-latest
    if: ${{ forgejo.repository == 'www/www-from-model' }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Prepare environment
        uses: https://hub.psychoinformatics.de/orinoco/flow/forgejo/actions/prep-metadata-query@main
      #- name: Debug
      #  run: |
      #    cat << EOT > /usr/local/bin/git-credential-echo
      #    #!/usr/bin/env bash
      #    exec cat >&2
      #    EOT
      #    chmod +x /usr/local/bin/git-credential-echo
      #    git config --global --add credential.helper echo
      - name: git-annex init
        run: |
          git fetch --depth 1 origin git-annex:git-annex
          git config --add annex.private true
          git annex init
      - name: Update navigation graph
        run: |
          dtc get-records ${DUMPTHINGS_APIURL} public \
          | query-things cache \
          | python3 code/pool2graph.py > static/graph.json_new \
          && mv static/graph.json_new static/graph.json \
          && git annex add static
      - name: Update objectives
        run: |
          query-things list --class xyzri:XYZObjective \
          | query-things inline-things -p part_of -c public \
          | query-things inline-things -p depends_on -c public \
          | query-things render-record page_templates/objective.md.j2 'content/{__pid_curie_reference}/_index.md'
      - name: Update topics
        run: |
          query-things list --class xyzri:XYZTopic \
          | query-things inline-things -p part_of -c public \
          | query-things render-record page_templates/topic.md.j2 'content/{__pid_curie_reference}/_index.md'
      - name: Update persons
        run: |
          query-things list --class xyzri:XYZPerson \
          | query-things filter-linked-pid public  xyzrins:. associated_with  \
          | query-things inline-things -c public -p delegated_by::object -p delegated_by::roles -p identifiers::creator \
          | query-things render-record page_templates/person.md.j2 \
            'content/{__pid_curie_reference}/_index.md'
      - name: Update projects
        run: |
          query-things list --class xyzri:XYZProject \
          | query-things filter-links-pid --link part_of xyzrins:. --recursive --collection public \
          | query-things inject-links-pid --link generated_by generated \
          | query-things inject-links-pid --link part_of parts \
          | query-things inline-things -c public -p associated_with::object -p associated_with::roles -p influenced_by::object -p influenced_by::roles -p identifiers::creator -p part_of \
          | query-things render-record page_templates/project.md.j2 'content/{__pid_curie_reference}/_index.md'
      - name: Update publications
        run: |
          query-things list --class xyzri:XYZPublication \
          | query-things inline-things -p about -p attributed_to::object -c public \
          | query-things render-record page_templates/publication.md.j2 \
            'content/{__pid_curie_reference}/_index.md'
      - name: Update instruments
        run: |
          query-things list --class xyzri:XYZInstrument \
          | query-things inline-things -p about -p attributed_to::object -p kind -p rules -c public \
          | query-things render-record page_templates/instrument.md.j2 \
            'content/{__pid_curie_reference}/_index.md'
      - name: Update datasets
        run: |
          query-things list --class xyzri:XYZDataset \
          | query-things inline-things -p about -p attributed_to::object -p kind -p rules -p characterized_by::object -c public \
          | query-things render-record page_templates/dataset.md.j2 \
            'content/{__pid_curie_reference}/_index.md'
      - name: Update frontpage
        run: |
          query-things list --pid xyzrins:. \
          | query-things inject-links-pid --link generated_by generated \
          | query-things inject-links-pid --link part_of parts \
          | query-things inline-things -c public -p associated_with::object -p associated_with::roles -p influenced_by::object -p influenced_by::roles -p identifiers::creator -p part_of \
          | query-things render-record page_templates/homepage.md.j2 'content/{__pid_curie_reference}/_index.md'
      - name: Deposit changes
        uses: https://hub.psychoinformatics.de/orinoco/flow/forgejo/actions/deposit-changes@main
      - name: Deposit annex keys
        run: |
          git annex push
          git annex push --cleanup
