name: Update project pages

on:
  schedule:
    - cron: '0 4 * * 1-5'
  workflow_dispatch:

env:
  DUMPTHINGS_APIURL: https://pool.psychoinformatics.de/api

jobs:
  create_pages:
    runs-on: debian-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Prepare environment
        uses: ./.forgejo/actions/prep-metadata-query
      - name: Update pages
        run: |
          dtc get-records $DUMPTHINGS_APIURL public -C XYZProject \
          | qri filter-links-pid --link part_of xyzrins:. --recursive --collection public \
          | qri inject-links-pid --link generated_by generated \
          | qri inject-links-pid --link part_of parts \
          | qri inline-records -c public -p associated_with -p associated_with::roles -p identifiers::creator -p part_of \
          | qri render-record page_templates/project.md.j2 'content/{__pid_curie_reference}/_index.md'
      - name: Deposit changes
        uses: ./.forgejo/actions/deposit-changes
