name: Update project pages

on:
  schedule:
    - cron: '0 4 * * 1-5'
  workflow_dispatch:

env:
  POOLAPI: https://pool.psychoinformatics.de/api

jobs:
  create_pages:
    runs-on: debian-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Prepare environment
        uses: ./.forgejo/actions/prep-metadata-query
      - name: Update pages
        run: |
          dtc read-pages ${POOLAPI}/public/records/p/XYZProject \
          | qrg filter-links-pid --link part_of xyzrsens:projects/4b434ab4-929e-4d64-97e0-ff334c6a6ff2 --recursive --api-url ${POOLAPI} --collection public \
          | qrg inline-records --api-url $POOLAPI -c public -p associated_with -p associated_with::roles -p identifiers::creator -p part_of \
          | qrg render-record page_templates/project.md.j2 'content/{__pid_curie_reference}/_index.md'
      - name: Deposit changes
        uses: ./.forgejo/actions/deposit-changes
