name: Update person pages

# run daily (5:15 on weekdays) and on manual dispatch
on:
  schedule:
    - cron: '15 5 * * 1-5'
  workflow_dispatch:

jobs:
  create_pages:
    runs-on: debian-latest
    if: ${{ forgejo.repository == 'www/www-from-model' }}
    outputs:
      committed: ${{ steps.commit.outputs.committed }}

    steps:
      - name: Checkout this
        id: websitecheckout
        uses: https://hub.datalad.org/forgejo/datalad-clone-action@v1
        with:
          ref: main
          get_file_content: false
          recursive: false

      # this step clones code for additional record processing and filtering.
      # TODO: that code needs to be generalized before being used here, maybe
      # also come from a more central/generic repo than the trr resources
      #- name: Checkout code
      #  id: codecheckout
      #  uses: https://hub.datalad.org/forgejo/datalad-clone-action@v1
      #  with:
      #    repository: https://hub.trr379.de/q02/pool-publication-page
      #    get_file_content: false

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install qrg & dtc suites, and git-annex
        run: |
          uv tool install https://hub.psychoinformatics.de/datalink/query-rse-group.git
          uv tool install dump-things-pyclient
          uv tool install git-annex

      - name: Configure Git
        run: |
          git config --global user.name ${{ forgejo.actor }}
          git config --global user.email ${{ forgejo.actor }}@${{ forgejo.server.url }}
          git config --global credential.helper cache
          git credential approve <<EOF
          url=${{ forgejo.server_url }}
          username=${{ forgejo.actor }}
          password=${{ forgejo.token }}
          EOF
          echo OK

      - name: Process metadata
        run: |
          dtc read-pages https://pool.psychoinformatics.de/api/public/records/p/XYZPerson \
          | qrg filter-linked-pid --api-url https://pool.psychoinformatics.de/api public  xyzrins:. associated_with  \
          | qrg inline-records --api-url https://pool.psychoinformatics.de/api -c public -p delegated_by -p delegated_by::roles -p identifiers::creator \
          | qrg render-record page_templates/person.md.j2 'content/{__pid_curie_reference}/_index.md'

      - name: Commit and push updates
        id: commit
        run: |
          git add content/persons
          git commit -m "auto-generate person pages" && result=t || result=nil
          git push origin
          echo "committed=${result}" >> $FORGEJO_OUTPUT
