name: Update topic pages

on:
  schedule:
    - cron: '34 5 * * 1-5'
  workflow_dispatch:

jobs:
  create_pages:
    runs-on: debian-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install tools
        run: .forgejo/tools/install_tools
      - name: Prepare Git
        run: .forgejo/tools/prep_git
      - name: Update pages
        run: |
          read-pages https://pool.psychoinformatics.de/api/public/records/p/XYZTopic \
          | grep 'xyzrsens:topics/' \
          | qrg inline-records -p part_of --api-url https://pool.psychoinformatics.de/api -c public \
          | qrg render-record page_templates/topic.md.j2 'content/{__pid_curie_reference}/_index.md'
      - name: Commit and push updates
        id: commit
        run: |
          git add content
          git diff --quiet --cached && echo "Already up-to-date" || ( git commit -m "feat: auto-generate topic pages" && git push origin )
