name: Update project pages

on:
  schedule:
    - cron: '0 4 * * 1-5'
  workflow_dispatch:

env:
  POOLAPI: https://pool.psychoinformatics.de/api

jobs:
  create_pages:
    runs-on: debian-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Prepare environment
        uses: ./.forgejo/actions/prep-metadata-query
      - name: Update pages
        run: |
          dtc get-records $POOLAPI public -C XYZProject \
          | qrg filter-links-pid --link part_of xyzrins:. --recursive --api-url ${POOLAPI} --collection public \
          | while read rec; do projpid="$(echo $rec | jq -r '.pid')"; echo "$rec" | jq -c ". + {generated: $(dtc get-records ${POOLAPI} public --matching "$projpid" | jq -c ". | select(.generated_by[]?.object == \"$projpid\")" | jq -c --slurp)}"; done \
          | qrg inline-records --api-url $POOLAPI -c public -p associated_with -p associated_with::roles -p identifiers::creator -p part_of \
          | qrg render-record page_templates/project.md.j2 'content/{__pid_curie_reference}/_index.md'
      - name: Deposit changes
        uses: ./.forgejo/actions/deposit-changes
