name: Update person pages

on:
  schedule:
    - cron: '0 3 * * 1-5'
  workflow_dispatch:

env:
  DUMPTHINGS_APIURL: https://pool.psychoinformatics.de/api

jobs:
  create_pages:
    runs-on: debian-latest
    if: ${{ forgejo.repository == 'www/www-from-model' }}
    outputs:
      committed: ${{ steps.commit.outputs.committed }}

    steps:
      - name: Checkout this
        id: websitecheckout
        uses: https://hub.datalad.org/forgejo/datalad-clone-action@v1
        with:
          ref: main
          get_file_content: false
          recursive: false
      - name: Prepare environment
        uses: ./.forgejo/actions/prep-metadata-query
      - name: Process metadata
        run: |
          dtc get-records ${DUMPTHINGS_APIURL} public -C XYZPerson \
          | qri filter-linked-pid public  xyzrins:. associated_with  \
          | qri inline-records -c public -p delegated_by -p delegated_by::roles -p identifiers::creator \
          | qri render-record page_templates/person.md.j2 \
            'content/{__pid_curie_reference}/_index.md'
      - name: Deposit changes
        uses: ./.forgejo/actions/deposit-changes
