name: Update objective pages

on:
  schedule:
    - cron: '0 2 * * 1-5'
  workflow_dispatch:

env:
  DUMPTHINGS_APIURL: https://pool.psychoinformatics.de/api

jobs:
  create_pages:
    runs-on: debian-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Prepare environment
        uses: ./.forgejo/actions/prep-metadata-query
      - name: Update pages
        run: |
          dtc get-records ${DUMPTHINGS_APIURL} public -C XYZObjective \
          | qrg inline-records -p part_of -c public \
          | qrg inline-records -p depends_on -c public \
          | qrg render-record page_templates/objective.md.j2 'content/{__pid_curie_reference}/_index.md'
      - name: Deposit changes
        uses: ./.forgejo/actions/deposit-changes
