name: Update person pages

# run daily (5:15 on weekdays) and on manual dispatch
on:
  schedule:
    - cron: '15 5 * * 1-5'
  workflow_dispatch:

jobs:
  create_pages:
    runs-on: debian-latest
    if: ${{ forgejo.repository == 'www/www-from-model' }}
    outputs:
      committed: ${{ steps.commit.outputs.committed }}

    steps:
      - name: Checkout this
        id: websitecheckout
        uses: https://hub.datalad.org/forgejo/datalad-clone-action@v1
        with:
          ref: main
          get_file_content: false
          recursive: false

      - name: Checkout code
        id: codecheckout
        uses: https://hub.datalad.org/forgejo/datalad-clone-action@v1
        with:
          repository: https://hub.trr379.de/q02/pool-publication-page
          get_file_content: false
          path: code

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install qrg & dtc suites, and git-annex
        run: |
          uv tool install https://hub.psychoinformatics.de/datalink/query-rse-group.git
          uv tool install dump-things-pyclient
          uv tool install git-annex

      - name: Configure Git
        run: |
          git config --global user.name "Forgejo Actions"
          git config --global user.email "forgejo-actions@hub.trr379.de"
          git config --global credential.helper cache
          git credential approve <<EOF
          url=${{ forgejo.server_url }}
          username=${{ forgejo.actor }}
          password=${{ forgejo.token }}
          EOF
          echo OK

      - name: Process metadata
        run: |
          cd ${{ steps.codecheckout.outputs.path }}
          uv sync --locked
          dtc read-pages https://pool.psychoinformatics.de/api/public/records/p/XYZPerson \
          | qrg filter-linked-pid --api-url https://pool.psychoinformatics.de/api public xyzrsens:projects/4b434ab4-929e-4d64-97e0-ff334c6a6ff2 associated_with \
          | qrg inline-records --api-url https://pool.psychoinformatics.de/api -c public -p delegated_by -p delegated_by::roles -p identifiers::creator \
          | uv run person.py - ${{ steps.websitecheckout.outputs.path }}/content/persons

      - name: Commit and push updates
        id: commit
        run: |
          git add content/persons
          git commit -m "auto-generate person pages" && result=t || result=nil
          git push origin
          echo "committed=${result}" >> $FORGEJO_OUTPUT
