#!/bin/sh

set -e -u

# use a single environment for all tools
uv tool install https://hub.psychoinformatics.de/datalink/query-rse-group.git \
  --with-executables-from dump-things-pyclient \
  --with-executables-from git-annex
# we need git-annex even when we are not working with annex keys
# the repository is annex-init'ed on-clone, so git-annex tooling
# runs in commit hooks
